codecov:
  branch: main
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

comment:
  behavior: default
  require_changes: false
  hide_project_coverage: true
